### ISSUE TITLE
it has only 1 staking contract can you provide all other's contracts

### ISSUE THREAD

**Issue by souravmaji1** [daffadevhosting/simpl-nft-marketplace#1]
it has only 1 staking contract , can you tell me where are the other contracts which i can connect with this marketplace to run into my pc

**Comment by daffadevhosting** [comment]
You can use thirdweb provider for other contracts and start development quickly, you can look at https://thirdweb.com/dashboard, use testnet first.

**Comment by daffadevhosting** [comment]
> it has only 1 staking contract , can you tell me where are the other contracts which i can connect with this marketplace to run into my pc

You can use thirdweb provider for other contracts and start development quickly, you can look at https://thirdweb.com/dashboard, use testnet first. 
Don't deploy the staking contract before you deploy the other, you need the other contract address for put in to staking contract.

**Comment by souravmaji1** [comment]
after i added all the addressess in the .env file and tried running the dapp in the localhost it is showing this and not opening in the localhost it is just getting ended 

![ss](https://user-images.githubusercontent.com/87080195/224322132-4e2d633c-698c-4363-83e3-0bbafbf8baaa.PNG)

**Comment by daffadevhosting** [comment]
> after i added all the addressess in the .env file and tried running the dapp in the localhost it is showing this and not opening in the localhost it is just getting ended
> 
> ![ss](https://user-images.githubusercontent.com/87080195/224322132-4e2d633c-698c-4363-83e3-0bbafbf8baaa.PNG)

Have you checked sample.env with const/contractAddresses.js to see if they are the same? and how about the installation of the json package? are successfull?

@souravmaji1 

use `.env.local` for developed do not `.env` 

`.env` just for `production..`

should look like this...

![Screenshot57](https://user-images.githubusercontent.com/79897029/224369862-3bb80cf1-33a1-4ed9-88ed-00497c57fe0c.png)

**Comment by souravmaji1** [comment]
i did .env for that reason might be the error

**Comment by souravmaji1** [comment]
I have changed to .env.local still not running in the local , basically I have runned npm install for downloading all packages and added all the contract addresses in the .env.local file then typed " npm run dev" all this I have done am i missing something ?

**Comment by souravmaji1** [comment]
![cco](https://user-images.githubusercontent.com/87080195/224371625-0fee66f5-22b2-45ea-9404-6ef48fc616ce.PNG)
![local](https://user-images.githubusercontent.com/87080195/224371641-a988696b-13d0-4248-8c68-69047c62020f.PNG)


this are my .env.local and const/contract-addrerss file

**Comment by daffadevhosting** [comment]
> ![cco](https://user-images.githubusercontent.com/87080195/224371625-0fee66f5-22b2-45ea-9404-6ef48fc616ce.PNG) ![local](https://user-images.githubusercontent.com/87080195/224371641-a988696b-13d0-4248-8c68-69047c62020f.PNG)
> 
> this are my .env.local and const/contract-addrerss file

@souravmaji1 goerli-testnet at chain `56` not at `137` check at `const/aLink.ts`

**Comment by souravmaji1** [comment]
done that then also same error , do i need to change anything inside the any file  ?

**Comment by daffadevhosting** [comment]
> done that then also same error , do i need to change anything inside the any file ?

@souravmaji1 What OS do you use Windows or Linux?

**Comment by souravmaji1** [comment]
windows

**Comment by daffadevhosting** [comment]
> windows
try deleting `package-lock.json` and `node_module` folder, then try reinstalling all packages with` npm install`.

**Comment by souravmaji1** [comment]
okay

**Comment by daffadevhosting** [comment]
> okay

if you may delete your private key atacment above.

**Comment by daffadevhosting** [comment]
> > okay
> 
> if you may delete your private key atacment above.

don't share your private key wallet to public.

**Comment by souravmaji1** [comment]
that is not the correct private key i Have deleted some words from the middle also I am removing the image

**Comment by daffadevhosting** [comment]
> that is not the correct private key i Have deleted some words from the middle also I am removing the image

oke

**Comment by souravmaji1** [comment]
same error , again am i missing any steps ?

**Comment by daffadevhosting** [comment]
> same error , again am i missing any steps ?

I don't know, maybe from the difference in computer OS, because I use Linux OS. if I move coding to Windows OS, there are some things that don't work properly. there always has to be a rearrangement in the package.

**Comment by daffadevhosting** [comment]
> > same error , again am i missing any steps ?
> 
> I don't know, maybe from the difference in computer OS, because I use Linux OS. if I move coding to Windows OS, there are some things that don't work properly. there always has to be a rearrangement in the package.

You can try installing the nextJs starter package. and move all required js components and files also package.json in to nextJS new folder. it should be start from zero.

**Comment by daffadevhosting** [comment]
@souravmaji1can you give me your email address, i will send my master project folder.

**Comment by daffadevhosting** [comment]
![Screenshot58](https://user-images.githubusercontent.com/79897029/224410111-666496a2-a206-48e6-9439-443177c3b9e1.png)

@souravmaji1 

to confirm the error, i tried clone the repo and install package, on linux everything works as it should, even without `.env.local` file. probably due to differences in computer OS. you can try fix up stream peer dependence

try this 
`npm install --legacy-peer-deps`
`npm audit fix --force`

**Comment by souravmaji1** [comment]
this is my email : majisourav810@gmail.com

**Comment by souravmaji1** [comment]
and I am trying your above solution let's see if that works

**Comment by souravmaji1** [comment]
I tried running this above commands it still give same error , now i am trying to create nextjs starter package and adding all those files and isnatlling depending starting from scartch hope this works

**Comment by daffadevhosting** [comment]
> I tried running this above commands it still give same error , now i am trying to create nextjs starter package and adding all those files and isnatlling depending starting from scartch hope this works

Oke.

**Comment by daffadevhosting** [comment]
@souravmaji1 
My suggestion in package.json remove react-3d-hover before installing the package. that package only runs on react 17. Then you can edit and remove all `<Hover` element in the every component, you will notice the error must be shown.

**Comment by souravmaji1** [comment]
sorry , it was my mistake I was using older version of nodejs for that reason it was giving error 

but now the main problem came , basically I want to ask you which are the contracts you have used using thriwed also any permission provided from any contract to another ( as I am getting error while listing nfts )

![ssss](https://user-images.githubusercontent.com/87080195/224474587-a4f1f541-8b56-4652-ad46-24388debe1d1.PNG)

**Comment by daffadevhosting** [comment]
> sorry , it was my mistake I was using older version of nodejs for that reason it was giving error
> 
> but now the main problem came , basically I want to ask you which are the contracts you have used using thriwed also any permission provided from any contract to another ( as I am getting error while listing nfts )
> 
> ![ssss](https://user-images.githubusercontent.com/87080195/224474587-a4f1f541-8b56-4652-ad46-24388debe1d1.PNG)


it's all in the README.md file at the bottom

### Contracts

- Staking Contract. (Custom)
- Marketplace Contracts.
- NFT Collection Contracts.
- NFTdrop Contracts.
- NFTedition Contracts. (memberpass)
- ERC20Token Contracts. (reward)

 Now staking contracts are also available on thirdweb.

**Comment by daffadevhosting** [comment]
I suggest using a smart contract from thirdweb, because if you use another contract provider you have to adjust the codes with the ABI smartcontract in the website component.

**Comment by souravmaji1** [comment]
yes , I am using all the contracts from thirdweb

**Comment by souravmaji1** [comment]
after I have deployed every contract correctly then also this error is showing  
![ssss](https://user-images.githubusercontent.com/87080195/224486256-8c6ff7af-e086-4c1c-8548-268afe79991a.PNG)


but I have noticed that this error comes into your dapp too , the link(vercel) of your dapp i tried uploading nfts when i set 0.001 it shows same error but when i changed the price to 0.1 it uploaded successfully and in my case whether i put 0.1 or 0.001 it still gives error and doesn't get uploaded

**Comment by daffadevhosting** [comment]
It always happens,  try to go to the pages/api folder, then open the file generate-mint-signature.js then in the line `const sdk = ThirdwebSDK.fromPrivateKey(process.env.PRIVATE_KEY, NETWORK_CHAIN_NAME);` remove `NETWORK_CHAIN_NAME` replace with original. whatever network you use. so it will look like this. `const sdk = ThirdwebSDK.fromPrivateKey(process.env.PRIVATE_KEY, "goerli-testnet");`

**Comment by daffadevhosting** [comment]
> after I have deployed every contract correctly then also this error is showing ![ssss](https://user-images.githubusercontent.com/87080195/224486256-8c6ff7af-e086-4c1c-8548-268afe79991a.PNG)
> 
> but I have noticed that this error comes into your dapp too , the link(vercel) of your dapp i tried uploading nfts when i set 0.001 it shows same error but when i changed the price to 0.1 it uploaded successfully and in my case whether i put 0.1 or 0.001 it still gives error and doesn't get uploaded

@souravmaji1 

It always happens,  try to go to the pages/api folder, then open the file generate-mint-signature.js then in the line `const sdk = ThirdwebSDK.fromPrivateKey(process.env.PRIVATE_KEY, NETWORK_CHAIN_NAME);` remove `NETWORK_CHAIN_NAME` replace with original. whatever network you use. so it will look like this. `const sdk = ThirdwebSDK.fromPrivateKey(process.env.PRIVATE_KEY, "goerli-testnet");`

**Comment by souravmaji1** [comment]
still getting the same error , do i need to replace anything in any other pages  ?

**Comment by souravmaji1** [comment]
can you provide your folder which you have used while running the dapp , so that i can see the error in my folder which I am making

**Comment by daffadevhosting** [comment]
> can you provide your folder which you have used while running the dapp , so that i can see the error in my folder which I am making

I have replaced it on my dapp, and it can upload immediately. the error in the console just leads to it.

**Comment by daffadevhosting** [comment]
> can you provide your folder which you have used while running the dapp , so that i can see the error in my folder which I am making

pages > api > generate-mint-signature.js

**Comment by souravmaji1** [comment]
Is this is correct ?

![ssw](https://user-images.githubusercontent.com/87080195/224503722-5e8bf65d-b2eb-4555-ad4b-2e956e90ad20.PNG)

**Comment by souravmaji1** [comment]
I am getting this error after i upload nft and click on mint+list button in the console 
![Capture](https://user-images.githubusercontent.com/87080195/224504371-6475d163-4c62-4ea9-a94c-83ed9971a675.PNG)

**Comment by souravmaji1** [comment]
basically , i am writing wrong chain name , what will be the chain name if i have deployed to bnb testnet 
as i have seen in the (alinks) page in the chain name section 97 chain id network name is BNBTestnet but is is giving error

![sr](https://user-images.githubusercontent.com/87080195/224505207-be936a8e-75f5-4895-86af-69cef45f3b95.PNG)

**Comment by souravmaji1** [comment]
added the correct name but lastly it is giving new error 

![ss](https://user-images.githubusercontent.com/87080195/224505693-e6390a8d-c3b3-4365-841b-704b793f48c0.PNG)

**Comment by daffadevhosting** [comment]
> basically , i am writing wrong chain name , what will be the chain name if i have deployed to bnb testnet as i have seen in the (alinks) page in the chain name section 97 chain id network name is BNBTestnet but is is giving error
> 
> ![sr](https://user-images.githubusercontent.com/87080195/224505207-be936a8e-75f5-4895-86af-69cef45f3b95.PNG)

Chain Name for BNB testnet is `binance-testnet`

**Comment by daffadevhosting** [comment]
> Is this is correct ?
> 
> ![ssw](https://user-images.githubusercontent.com/87080195/224503722-5e8bf65d-b2eb-4555-ad4b-2e956e90ad20.PNG)

Which network do you deploy smart contracts on thirdweb? use the same network address as the smart contract you deployed.

**Comment by souravmaji1** [comment]
hi , I have solved the error and it is working smoothly and I would thank you for bring supportive and guiding me along with this project

thanks a lot


![sssd](https://user-images.githubusercontent.com/87080195/224507929-393d1e12-0b63-4953-874b-27696a49f172.PNG)

**Comment by daffadevhosting** [comment]
> hi , I have solved the error and it is working smoothly and I would thank you for bring supportive and guiding me along with this project
> 
> thanks a lot
> 
> ![sssd](https://user-images.githubusercontent.com/87080195/224507929-393d1e12-0b63-4953-874b-27696a49f172.PNG)

oke.. nice.. happy codding
